[manifest]
id = "slow_dk_phase"
version = "1.0.0"
display_name = "Slow DK Phase"
description = "Slows DK Phase down so that the window to hit K Rool is wider"
short_description = "Slows DK Phase down so that the window to hit K Rool is wider"
authors = [ "Ballaam" ]
game_id = "dk64"
minimum_recomp_version = "1.0.0"

[inputs]
elf_path = "build/mod.elf"
mod_filename = "slow_dk_phase"
func_reference_syms_file = "Dk64Syms/dump.toml"
data_reference_syms_files = [ "Dk64Syms/data_dump.toml" ]
additional_files = ["thumb.dds"]
